export const ServiceData = [
  {
    id: 1,
    slug: "design-consultation",
    title: "Design Consultation",
    h1: "Professional Design Consultation Services",
    alt: "Design Consultation Services",
    img: [
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    ],
    descp: `<p>We begin by understanding your space, lifestyle, and preferences through detailed discussions.</p>`,
    descp2: `<p>Mood boards and concept ideas are developed to align design direction with your expectations.</p>`,
    descp3: `<p>We analyze spatial constraints, functional needs, and budget considerations.</p>`,
    descp4: `<p>This phase helps eliminate uncertainty before moving into design execution.</p>`,
    descp5: `<p>Our consultation ensures clarity, confidence, and a strong foundation for your project.</p>`,
  },

  {
    id: 2,
    slug: "residential-interiors",
    title: "Residential Interiors",
    h1: "Residential Interior Design Services",
    alt: "Residential Interior Design",
    img: [
      "https://source.unsplash.com/800x600/?home,interior",
      "https://source.unsplash.com/800x600/?living-room,interior",
    ],
    descp: `<p>We design personalized homes that balance beauty, comfort, and practicality.</p>`,
    descp2: `<p>Our residential services include living rooms, bedrooms, kitchens, and bathrooms.</p>`,
    descp3: `<p>Each design reflects your lifestyle, taste, and daily routines.</p>`,
    descp4: `<p>We carefully select materials, colors, and finishes for lasting appeal.</p>`,
    descp5: `<p>The result is a warm, functional home tailored exclusively to you.</p>`,
  },

  {
    id: 3,
    slug: "commercial-interiors",
    title: "Commercial Interiors",
    h1: "Commercial Interior Design Services",
    alt: "Commercial Interior Design",
    img: [
      "https://source.unsplash.com/800x600/?office,interior",
      "https://source.unsplash.com/800x600/?restaurant,interior",
    ],
    descp: `<p>We create commercial spaces that enhance brand identity and efficiency.</p>`,
    descp2: `<p>Our designs focus on workflow optimization and customer experience.</p>`,
    descp3: `<p>We work on offices, retail outlets, restaurants, and showrooms.</p>`,
    descp4: `<p>Every design balances aesthetics with operational requirements.</p>`,
    descp5: `<p>The outcome is a professional, inspiring, and functional workspace.</p>`,
  },

  {
    id: 4,
    slug: "turnkey-solutions",
    title: "Turnkey Solutions",
    h1: "End-to-End Turnkey Interior Solutions",
    alt: "Turnkey Interior Solutions",
    img: [
      "https://source.unsplash.com/800x600/?interior,construction",
      "https://source.unsplash.com/800x600/?interior,execution",
    ],
    descp: `<p>Our turnkey solutions manage your project from concept to completion.</p>`,
    descp2: `<p>We handle materials, vendors, timelines, and site supervision.</p>`,
    descp3: `<p>Clients benefit from a single point of responsibility.</p>`,
    descp4: `<p>Quality control and timely execution are our top priorities.</p>`,
    descp5: `<p>You receive a ready-to-use space without stress or delays.</p>`,
  },

  {
    id: 5,
    slug: "space-planning-3d-visualization",
    title: "Space Planning & 3D Visualization",
    h1: "Space Planning & 3D Visualization Services",
    alt: "3D Interior Visualization",
    img: [
      "https://source.unsplash.com/800x600/?3d,interior",
      "https://source.unsplash.com/800x600/?floor-plan,interior",
    ],
    descp: `<p>Smart space planning ensures optimal use of every square foot.</p>`,
    descp2: `<p>We create detailed 2D layouts for functional clarity.</p>`,
    descp3: `<p>High-quality 3D renders provide realistic visual previews.</p>`,
    descp4: `<p>This helps in better material and layout decisions.</p>`,
    descp5: `<p>Clients gain confidence before moving into execution.</p>`,
  },

  {
    id: 6,
    slug: "custom-furniture-decor",
    title: "Custom Furniture & Décor",
    h1: "Custom Furniture & Décor Design",
    alt: "Custom Furniture and Decor",
    img: [
      "https://source.unsplash.com/800x600/?custom-furniture",
      "https://source.unsplash.com/800x600/?home-decor",
    ],
    descp: `<p>We design custom furniture tailored to your space and style.</p>`,
    descp2: `<p>Décor elements are carefully curated for visual harmony.</p>`,
    descp3: `<p>Materials and finishes are chosen for durability and comfort.</p>`,
    descp4: `<p>Every piece enhances both aesthetics and usability.</p>`,
    descp5: `<p>The result is a cohesive and elegant interior environment.</p>`,
  },

  {
    id: 7,
    slug: "renovation-remodeling",
    title: "Renovation & Remodeling",
    h1: "Renovation & Remodeling Services",
    alt: "Interior Renovation Services",
    img: [
      "https://source.unsplash.com/800x600/?renovation,interior",
      "https://source.unsplash.com/800x600/?home-remodel",
    ],
    descp: `<p>We transform outdated spaces into modern, functional interiors.</p>`,
    descp2: `<p>Renovation solutions are tailored to your needs and budget.</p>`,
    descp3: `<p>Structural upgrades and aesthetic improvements go hand in hand.</p>`,
    descp4: `<p>Minimal disruption and efficient execution are ensured.</p>`,
    descp5: `<p>Your space gains renewed value and comfort.</p>`,
  },

  {
    id: 8,
    slug: "sustainable-smart-design",
    title: "Sustainable & Smart Design",
    h1: "Sustainable & Smart Interior Design",
    alt: "Sustainable Interior Design",
    img: [
      "https://source.unsplash.com/800x600/?sustainable,interior",
      "https://source.unsplash.com/800x600/?smart-home",
    ],
    descp: `<p>We design eco-conscious interiors with future-ready solutions.</p>`,
    descp2: `<p>Energy-efficient lighting and materials are thoughtfully integrated.</p>`,
    descp3: `<p>Smart technology enhances comfort and convenience.</p>`,
    descp4: `<p>Our designs reduce environmental impact responsibly.</p>`,
    descp5: `<p>The result is a sustainable, intelligent living space.</p>`,
  },

  {
    id: 9,
    slug: "project-management-execution",
    title: "Project Management & Execution",
    h1: "Interior Project Management & Execution",
    alt: "Interior Project Management",
    img: [
      "https://source.unsplash.com/800x600/?interior,project-management",
      "https://source.unsplash.com/800x600/?construction,interior",
    ],
    descp: `<p>We manage your project with precision and transparency.</p>`,
    descp2: `<p>Our team coordinates vendors, schedules, and site activities.</p>`,
    descp3: `<p>Regular quality checks ensure flawless execution.</p>`,
    descp4: `<p>Budgets and timelines are strictly maintained.</p>`,
    descp5: `<p>You receive a smooth, hassle-free project delivery.</p>`,
  },
];
